### ISSUE TITLE
Saml2MetadataFilter Compilation error

### ISSUE THREAD

**Issue by byper** [pac4j/j2e-pac4j-demo#22]
The method ```internalFilter``` called ```ConfigSingleton.getConfig().getClients().findClient``` sending parameters of type String but requires the type ```org.pac4j.core.context.WebContext```

**Comment by leleuj** [comment]
You're right: the latest update on pac4j v1.8.1 broke the demo (hopefully not the j2e-pac4j library itself).
It's fixed: https://github.com/pac4j/j2e-pac4j-demo/commit/d8d903ccaa85d7284104041b3a32a5266d0508f9
