### ISSUE TITLE
Is multi profiles working as expected in the demo?

### ISSUE THREAD

**Issue by victornoel** [pac4j/j2e-pac4j-demo#25]
Hi,

I have been playing with this demo and I wonder if it is working as expected regarding multi profiles...

Basically, I saw that multi profiles was enabled, but I couldn't succeed in having multiple profiles at the same time... I may misunderstand the meaning of it, but I tried the following:
 - go to the form protected page
 - login with form
 - go to the facebook protected page

and I wasn't asked to login with facebook... is it expected? I would have thought that only the facebook client would allow me to access this page? no?

**Comment by millross** [comment]
I don't know the j2e demo but in the play version of the demo there's a "force Facebook login" near the bottom of the page.

The idea is that you log in through some (indirect) mechanism other than Facebook first, then click on the "Force Facebook login" link. That should then leave you with two profiles in the profiles list. I hope this is a clear explanation

**Comment by millross** [comment]
Looking at the j2e-pac4j demo source it looks as though the same link is present in the j2e pac4j demo.

**Comment by leleuj** [comment]
Exactly, you should log in with Twitter and then click on the "Force Facebook login" to be authenticated both with Facebook and Twitter.

The protected URLs expect the user to be authenticated, so as soon as one login has been performed, no other one will be requested. You can, of course, change this behavior in the demo, but this is the most common expected use case.

So it works as expected ;-)

**Comment by victornoel** [comment]
great, thanks for the explanation both of you :)
